export const PWD_REQUEST_APPLICATIONS = 'PWD_REQUEST_APPLICATIONS'
export const PWD_RECEIVE_APPLICATIONS = 'PWD_RECEIVE_APPLICATIONS'

export const PWD_SELECT_APPLICATION = 'PWD_SELECT_APPLICATION'
export const PWD_REQUEST_APPLICATION = 'PWD_REQUEST_APPLICATION'
export const PWD_RECEIVE_APPLICATION = 'PWD_RECEIVE_APPLICATION'

export const PWD_REQUEST_ACCOUNTS = 'PWD_REQUEST_ACCOUNTS'
export const PWD_RECEIVE_ACCOUNTS = 'PWD_RECEIVE_ACCOUNTS'

export const PWD_REQUEST_PASSWORD_REVEAL = 'PWD_REQUEST_PASSWORD_REVEAL'
export const PWD_RECEIVE_PASSWORD_REVEAL = 'PWD_RECEIVE_PASSWORD_REVEAL'

export const PWD_EMPTY_PLAIN_PASSWORD = 'PWD_EMPTY_PLAIN_PASSWORD'
export const PWD_REQUEST_GENERATE_PASSWORD = 'PWD_REQUEST_GENERATE_PASSWORD'
export const PWD_RECEIVE_GENERATE_PASSWORD = 'PWD_RECEIVE_GENERATE_PASSWORD'

export const PWD_UPDATE_PASSWORD = 'PWD_UPDATE_PASSWORD'
export const PWD_REQUEST_UPDATE_PASSWORD = 'PWD_REQUEST_UPDATE_PASSWORD'
export const PWD_RECEIVE_UPDATE_PASSWORD = 'PWD_RECEIVE_UPDATE_PASSWORD'

export const PWD_REQUEST_CREATE_ACCOUNT = 'PWD_REQUEST_CREATE_ACCOUNT'
export const PWD_RECEIVE_CREATE_ACCOUNT = 'PWD_RECEIVE_CREATE_ACCOUNT'

export const PWD_OPEN_ACCOUNT_DIALOG = 'PWD_OPEN_ACCOUNT_DIALOG'
export const PWD_CLOSE_ACCOUNT_DIALOG = 'PWD_CLOSE_ACCOUNT_DIALOG'
