export const PWD_REQUEST_APPLICATIONS = 'PWD_REQUEST_APPLICATIONS';
export const PWD_RECEIVE_APPLICATIONS = 'PWD_RECEIVE_APPLICATIONS';
export const PWD_SELECT_APPLICATION = 'PWD_SELECT_APPLICATION';
export const PWD_REQUEST_APPLICATION = 'PWD_REQUEST_APPLICATION';
export const PWD_RECEIVE_APPLICATION = 'PWD_RECEIVE_APPLICATION';
export const PWD_REQUEST_PASSWORD_REVEAL = 'PWD_REQUEST_PASSWORD_REVEAL';
export const PWD_RECEIVE_PASSWORD_REVEAL = 'PWD_RECEIVE_PASSWORD_REVEAL';
